spring:
  application:
    name: data-reader
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

data-reader:
  kafka:
    topic: ${KAFKA_TOPIC:geoname-events}
  file:
    path: ${DATA_FILE_PATH:./data/geonames.json}
